import './firebase-config.js';
import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import { getFirestore, collection, getDocs, setDoc, doc, deleteDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';

const ADMIN_EMAIL='santoshrawani123@gmail.com';
const KEY='sfh-products';
const app=getApps().length?getApps()[0]:initializeApp(window.SFH_FIREBASE_CONFIG);
const auth=getAuth(app); const db=getFirestore(app);
let products=[]; let currentUser=null;
const $=id=>document.getElementById(id);
const status=(text,type='')=>{const e=$('status');e.textContent=text;e.className='status '+type};
const authStatus=(text,type='')=>{const e=$('authStatus');e.textContent=text;e.className='status '+type};
const esc=v=>String(v??'').replace(/[&<>\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
const normalise=p=>({...p,id:String(p.id||('P'+Date.now())),images:Array.isArray(p.images)?p.images.filter(Boolean).slice(0,5):(p.image?[p.image]:[]),sizes:Array.isArray(p.sizes)?p.sizes:[]});
function mirror(){localStorage.setItem(KEY,JSON.stringify(products));}
function stats(){ $('count').textContent=products.length; $('units').textContent=products.reduce((n,p)=>n+(Number(p.stock)||0),0); $('outs').textContent=products.filter(p=>(Number(p.stock)||0)<=0).length; }
function card(p,i){const im=p.images||[];return `<article class="card"><div class="row"><div><b>${esc(p.name||'New Product')}</b><small>${esc(p.id)}</small></div><span class="pill ${(Number(p.stock)||0)>0?'in':'out'}">${(Number(p.stock)||0)>0?'IN STOCK':'OUT'}</span></div><div class="photo">${im[0]?`<img src="${im[0]}" alt="${esc(p.name)}" referrerpolicy="no-referrer">`:'📸 Add photo'}</div><div class="fields"><label>Product ID<input data-i="${i}" data-k="id" value="${esc(p.id)}"></label><label>Category<select data-i="${i}" data-k="cat">${['Men','Kids','Ladies','Jeans','T-Shirt','Shirt','Trouser','Jacket','Ethnic','Activewear','Innerwear','Accessories'].map(x=>`<option ${x===p.cat?'selected':''}>${x}</option>`).join('')}</select></label><label class="full">Product Name<input data-i="${i}" data-k="name" value="${esc(p.name)}"></label><label>Selling Price ₹<input type="number" data-i="${i}" data-k="price" value="${Number(p.price)||0}"></label><label>MRP ₹<input type="number" data-i="${i}" data-k="old" value="${Number(p.old)||0}"></label><label>Stock Qty<input type="number" data-i="${i}" data-k="stock" value="${Number(p.stock)||0}"></label><label>Tag<input data-i="${i}" data-k="tag" value="${esc(p.tag||'NEW')}"></label><label class="full">Sizes (comma separated)<input data-i="${i}" data-k="sizes" value="${esc((p.sizes||[]).join(', '))}"></label><label class="full">Description<textarea data-i="${i}" data-k="desc">${esc(p.desc||'')}</textarea></label></div><div class="photos"><label class="upload">📷 Front<input type="file" accept="image/*" data-photo="${i}"></label><span>${im.length} photo(s) saved</span></div><div class="actions"><button class="btn gold" data-save="${i}">Save Product</button><button class="btn danger" data-del="${i}">Delete</button></div></article>`}
function render(){const q=($('search').value||'').toLowerCase();const f=$('filter').value;const arr=products.map((p,i)=>({p,i})).filter(x=>(f==='All'||x.p.cat===f||x.p.group===f)&&(!q||`${x.p.id} ${x.p.name} ${x.p.cat}`.toLowerCase().includes(q)));$('list').innerHTML=arr.length?arr.map(x=>card(x.p,x.i)).join(''):'<div class="empty">No products. Click + Add Product.</div>';stats();bind();}
function bind(){document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>save(Number(b.dataset.save)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>remove(Number(b.dataset.del)));document.querySelectorAll('[data-photo]').forEach(x=>x.onchange=()=>photo(Number(x.dataset.photo),x.files[0]));document.querySelectorAll('[data-i]').forEach(x=>x.onchange=()=>{const i=Number(x.dataset.i),k=x.dataset.k;let v=x.value;if(['price','old','stock'].includes(k))v=Math.max(0,Number(v)||0);if(k==='sizes')v=v.split(',').map(s=>s.trim()).filter(Boolean);products[i]={...products[i],[k]:v};});}
async function save(i){try{const p=normalise(products[i]);await setDoc(doc(db,'products',p.id),{...p,updatedAt:serverTimestamp(),updatedBy:currentUser.uid});products[i]=p;mirror();render();status('Product saved in Firebase: '+p.id,'ok');}catch(e){console.error(e);status('Save failed: '+(e.code||e.message),'bad');alert((e.code||'error')+'\n'+e.message);}}
async function remove(i){if(!confirm('Delete '+products[i].id+' from Firebase?'))return;try{await deleteDoc(doc(db,'products',products[i].id));products.splice(i,1);mirror();render();status('Product deleted','ok');}catch(e){status('Delete failed: '+e.message,'bad');}}
async function add(){if(!currentUser){alert('Please sign in first.');return}const p=normalise({id:'P'+Date.now(),cat:'T-Shirt',group:'Men',name:'New Product',price:0,old:0,tag:'NEW',desc:'',sizes:['M','L','XL'],stock:0,image:'',images:[]});try{await setDoc(doc(db,'products',p.id),{...p,updatedAt:serverTimestamp(),updatedBy:currentUser.uid});products.unshift(p);mirror();render();status('New product added. Fill details and click Save Product.','ok');}catch(e){status('Add failed: '+e.message,'bad');alert(e.message);}}
async function photo(i,file){if(!file)return;try{const data=await resize(file);const p=products[i];p.images=[data,...(p.images||[]).filter(Boolean)].slice(0,5);p.image=p.images[0];await save(i);}catch(e){alert(e.message)}}
function resize(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1000,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,im.width*s);c.height=Math.max(1,im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);let q=.75,out=c.toDataURL('image/jpeg',q);while(out.length>140000&&q>.35){q-=.05;out=c.toDataURL('image/jpeg',q)}resolve(out)};im.onerror=()=>reject(new Error('Image could not be read'));im.src=r.result};r.onerror=()=>reject(new Error('File could not be read'));r.readAsDataURL(file);});}
async function load(){status('Loading products from Firebase…');try{const snap=await getDocs(collection(db,'products'));products=snap.docs.map(d=>normalise(d.data()));mirror();render();status('Firebase connected • '+products.length+' products','ok');}catch(e){console.error(e);status('Firebase error: '+(e.code||e.message),'bad');alert((e.code||e.message));}}
function addVisualPortal(){
  if(document.getElementById('sfhAdminVisualPortal'))return;
  const U='https://images.unsplash.com/';
  const map=[
    ['Men','Men’s Wear',U+'photo-1768696082704-c4e5593d9f27?auto=format&fit=crop&w=900&q=85'],
    ['Ladies','Women’s Wear',U+'photo-1692992193981-d3d92fabd9cb?auto=format&fit=crop&w=900&q=85'],
    ['Kids','Kids’ Wear',U+'photo-1744807561461-00bbe2419a65?auto=format&fit=crop&w=900&q=85'],
    ['Jeans','Jeans',U+'photo-1707400131124-a688ed508a95?auto=format&fit=crop&w=900&q=85'],
    ['T-Shirt','T-Shirts',U+'photo-1604534609306-00cdac972ad2?auto=format&fit=crop&w=900&q=85'],
    ['Shirt','Shirts',U+'photo-1715865717728-298d1925e4c6?auto=format&fit=crop&w=900&q=85'],
    ['Trouser','Trousers',U+'photo-1774414489671-9f33b8dff0a9?auto=format&fit=crop&w=900&q=85'],
    ['Jacket','Jackets',U+'photo-1604534609306-00cdac972ad2?auto=format&fit=crop&w=900&q=85'],
    ['Ethnic','Ethnic Wear',U+'photo-1572470176170-98fa8abcb741?auto=format&fit=crop&w=900&q=85'],
    ['Activewear','Activewear',U+'photo-1774414489671-9f33b8dff0a9?auto=format&fit=crop&w=900&q=85'],
    ['Innerwear','Innerwear',U+'photo-1774414489671-9f33b8dff0a9?auto=format&fit=crop&w=900&q=85'],
    ['Accessories','Accessories',U+'photo-1707400131124-a688ed508a95?auto=format&fit=crop&w=900&q=85']
  ];
  const wrap=document.createElement('section');wrap.id='sfhAdminVisualPortal';wrap.className='sfh-admin-visual';
  wrap.innerHTML=`<div class="sfh-av-head"><div><span>VISUAL STORE PORTAL</span><h2>Real Fashion Photo Categories</h2><p>Premium real-photo category gallery. These same photo categories are now used by the public storefront.</p></div><a href="./index.html" target="_blank">Open Main Store ↗</a></div><div class="sfh-av-grid">${map.map(([key,title,img])=>`<button class="sfh-av-card" data-av-filter="${key}"><img src="${img}" alt="${title}" loading="lazy" referrerpolicy="no-referrer"><span>${title}</span><small>Manage products →</small></button>`).join('')}</div>`;
  const manager=$('managerPanel');manager.parentNode.insertBefore(wrap,manager.nextSibling);
  wrap.querySelectorAll('[data-av-filter]').forEach(b=>b.onclick=()=>{const key=b.dataset.avFilter;const filter=[...$('filter').options].find(o=>o.value===key);if(filter){$('filter').value=key;render();$('list').scrollIntoView({behavior:'smooth',block:'start'});}else{status('Category '+key+' is available for product setup','ok');}});
  const st=document.createElement('style');st.textContent=`
  .sfh-admin-visual{margin:0 0 18px;padding:18px;border:1px solid #dfe3ea;border-radius:20px;background:linear-gradient(145deg,#fff,#f7f8fb);box-shadow:0 14px 38px rgba(11,16,32,.08)}
  .sfh-av-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;margin-bottom:14px;flex-wrap:wrap}.sfh-av-head span{font-size:10px;font-weight:950;letter-spacing:1.5px;color:#6548d8}.sfh-av-head h2{margin:4px 0 5px;font-size:22px}.sfh-av-head p{margin:0;color:#667085;font-size:12px;line-height:1.55;max-width:760px}.sfh-av-head a{background:#0b1020;color:#fff;text-decoration:none;padding:10px 13px;border-radius:10px;font-size:11px;font-weight:900}.sfh-av-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px}.sfh-av-card{border:1px solid #dfe3ea;background:#fff;border-radius:14px;padding:0;overflow:hidden;text-align:left;cursor:pointer;transition:.18s;box-shadow:0 5px 16px rgba(11,16,32,.05)}.sfh-av-card:hover{transform:translateY(-3px);box-shadow:0 12px 24px rgba(11,16,32,.12);border-color:#6548d8}.sfh-av-card img{width:100%;height:145px;display:block;object-fit:cover;background:#f2f3f7}.sfh-av-card span{display:block;padding:9px 9px 2px;font-size:12px;font-weight:950}.sfh-av-card small{display:block;padding:0 9px 10px;color:#667085;font-size:9px;font-weight:800}@media(max-width:1000px){.sfh-av-grid{grid-template-columns:repeat(4,1fr)}}@media(max-width:650px){.sfh-av-grid{grid-template-columns:repeat(2,1fr)}.sfh-av-card img{height:165px}}
  `;document.head.appendChild(st);
}
$('signin').onclick=async()=>{try{const email=$('email').value.trim().toLowerCase(),pass=$('password').value;if(!email||!pass)throw new Error('Enter email and password.');await signInWithEmailAndPassword(auth,email,pass);}catch(e){authStatus((e.code||'error')+' — '+e.message,'bad');}};
$('signup').onclick=async()=>{try{const email=$('email').value.trim().toLowerCase(),pass=$('password').value;if(!email||pass.length<6)throw new Error('Enter email and a password of at least 6 characters.');await createUserWithEmailAndPassword(auth,email,pass);}catch(e){authStatus((e.code||'error')+' — '+e.message,'bad');}};
$('logout').onclick=()=>signOut(auth);$('addTop').onclick=add;$('search').oninput=render;$('filter').onchange=render;
onAuthStateChanged(auth,async u=>{currentUser=u;if(!u){$('loginPanel').style.display='block';$('managerPanel').style.display='none';$('logout').style.display='none';authStatus('Please sign in with the admin email: '+ADMIN_EMAIL,'');return;}if((u.email||'').toLowerCase()!==ADMIN_EMAIL){$('loginPanel').style.display='block';$('managerPanel').style.display='none';$('logout').style.display='inline-block';authStatus('Signed in as '+u.email+', but this account is not the Product Manager admin. Use '+ADMIN_EMAIL+'.','bad');return;}$('loginPanel').style.display='none';$('managerPanel').style.display='block';$('logout').style.display='inline-block';addVisualPortal();await load();});
