import './firebase-config.js';
import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import { getFirestore, collection, getDocs, setDoc, doc, deleteDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';

const ADMIN_EMAIL='santoshrawani123@gmail.com';
const KEY='sfh-products';
const app=getApps().length?getApps()[0]:initializeApp(window.SFH_FIREBASE_CONFIG);
const auth=getAuth(app); const db=getFirestore(app);
let products=[]; let currentUser=null;
const $=id=>document.getElementById(id);
const status=(text,type='')=>{const e=$('status');e.textContent=text;e.className='status '+type};
const authStatus=(text,type='')=>{const e=$('authStatus');e.textContent=text;e.className='status '+type};
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
const normalise=p=>({...p,id:String(p.id||('P'+Date.now())),images:Array.isArray(p.images)?p.images.filter(Boolean).slice(0,5):(p.image?[p.image]:[]),sizes:Array.isArray(p.sizes)?p.sizes:[]});
function mirror(){localStorage.setItem(KEY,JSON.stringify(products));}
function stats(){ $('count').textContent=products.length; $('units').textContent=products.reduce((n,p)=>n+(Number(p.stock)||0),0); $('outs').textContent=products.filter(p=>(Number(p.stock)||0)<=0).length; }
function card(p,i){const im=p.images||[];return `<article class="card"><div class="row"><div><b>${esc(p.name||'New Product')}</b><small>${esc(p.id)}</small></div><span class="pill ${(Number(p.stock)||0)>0?'in':'out'}">${(Number(p.stock)||0)>0?'IN STOCK':'OUT'}</span></div><div class="photo">${im[0]?`<img src="${im[0]}" alt="${esc(p.name)}">`:'📸 Add photo'}</div><div class="fields"><label>Product ID<input data-i="${i}" data-k="id" value="${esc(p.id)}"></label><label>Category<select data-i="${i}" data-k="cat">${['Men','Kids','Ladies','Jeans','T-Shirt','Shirt','Trouser','Jacket'].map(x=>`<option ${x===p.cat?'selected':''}>${x}</option>`).join('')}</select></label><label class="full">Product Name<input data-i="${i}" data-k="name" value="${esc(p.name)}"></label><label>Selling Price ₹<input type="number" data-i="${i}" data-k="price" value="${Number(p.price)||0}"></label><label>MRP ₹<input type="number" data-i="${i}" data-k="old" value="${Number(p.old)||0}"></label><label>Stock Qty<input type="number" data-i="${i}" data-k="stock" value="${Number(p.stock)||0}"></label><label>Tag<input data-i="${i}" data-k="tag" value="${esc(p.tag||'NEW')}"></label><label class="full">Sizes (comma separated)<input data-i="${i}" data-k="sizes" value="${esc((p.sizes||[]).join(', '))}"></label><label class="full">Description<textarea data-i="${i}" data-k="desc">${esc(p.desc||'')}</textarea></label></div><div class="photos"><label class="upload">📷 Front<input type="file" accept="image/*" data-photo="${i}"></label><span>${im.length} photo(s) saved</span></div><div class="actions"><button class="btn gold" data-save="${i}">Save Product</button><button class="btn danger" data-del="${i}">Delete</button></div></article>`}
function render(){const q=($('search').value||'').toLowerCase();const f=$('filter').value;const arr=products.map((p,i)=>({p,i})).filter(x=>(f==='All'||x.p.cat===f||x.p.group===f)&&(!q||`${x.p.id} ${x.p.name} ${x.p.cat}`.toLowerCase().includes(q)));$('list').innerHTML=arr.length?arr.map(x=>card(x.p,x.i)).join(''):'<div class="empty">No products. Click + Add Product.</div>';stats();bind();}
function bind(){document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>save(Number(b.dataset.save)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>remove(Number(b.dataset.del)));document.querySelectorAll('[data-photo]').forEach(x=>x.onchange=()=>photo(Number(x.dataset.photo),x.files[0]));document.querySelectorAll('[data-i]').forEach(x=>x.onchange=()=>{const i=Number(x.dataset.i),k=x.dataset.k;let v=x.value;if(['price','old','stock'].includes(k))v=Math.max(0,Number(v)||0);if(k==='sizes')v=v.split(',').map(s=>s.trim()).filter(Boolean);products[i]={...products[i],[k]:v};});}
async function save(i){try{const p=normalise(products[i]);await setDoc(doc(db,'products',p.id),{...p,updatedAt:serverTimestamp(),updatedBy:currentUser.uid});products[i]=p;mirror();render();status('Product saved in Firebase: '+p.id,'ok');}catch(e){console.error(e);status('Save failed: '+(e.code||e.message),'bad');alert((e.code||'error')+'\n'+e.message);}}
async function remove(i){if(!confirm('Delete '+products[i].id+' from Firebase?'))return;try{await deleteDoc(doc(db,'products',products[i].id));products.splice(i,1);mirror();render();status('Product deleted','ok');}catch(e){status('Delete failed: '+e.message,'bad');}}
async function add(){if(!currentUser){alert('Please sign in first.');return}const p=normalise({id:'P'+Date.now(),cat:'T-Shirt',group:'Men',name:'New Product',price:0,old:0,tag:'NEW',desc:'',sizes:['M','L','XL'],stock:0,image:'',images:[]});try{await setDoc(doc(db,'products',p.id),{...p,updatedAt:serverTimestamp(),updatedBy:currentUser.uid});products.unshift(p);mirror();render();status('New product added. Fill details and click Save Product.','ok');}catch(e){status('Add failed: '+e.message,'bad');alert(e.message);}}
async function photo(i,file){if(!file)return;try{const data=await resize(file);const p=products[i];p.images=[data,...(p.images||[]).filter(Boolean)].slice(0,5);p.image=p.images[0];await save(i);}catch(e){alert(e.message)}}
function resize(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1000,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,im.width*s);c.height=Math.max(1,im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);let q=.75,out=c.toDataURL('image/jpeg',q);while(out.length>140000&&q>.35){q-=.05;out=c.toDataURL('image/jpeg',q)}resolve(out)};im.onerror=()=>reject(new Error('Image could not be read'));im.src=r.result};r.onerror=()=>reject(new Error('File could not be read'));r.readAsDataURL(file);});}
async function load(){status('Loading products from Firebase…');try{const snap=await getDocs(collection(db,'products'));products=snap.docs.map(d=>normalise(d.data()));mirror();render();status('Firebase connected • '+products.length+' products','ok');}catch(e){console.error(e);status('Firebase error: '+(e.code||e.message),'bad');alert((e.code||'firebase-error')+'\n'+e.message);}}
$('signin').onclick=async()=>{try{const email=$('email').value.trim().toLowerCase(),pass=$('password').value;if(!email||!pass)throw new Error('Enter email and password.');await signInWithEmailAndPassword(auth,email,pass);}catch(e){authStatus((e.code||'error')+' — '+e.message,'bad');}};
$('signup').onclick=async()=>{try{const email=$('email').value.trim().toLowerCase(),pass=$('password').value;if(!email||pass.length<6)throw new Error('Enter email and a password of at least 6 characters.');await createUserWithEmailAndPassword(auth,email,pass);}catch(e){authStatus((e.code||'error')+' — '+e.message,'bad');}};
$('logout').onclick=()=>signOut(auth);$('addTop').onclick=add;$('search').oninput=render;$('filter').onchange=render;
onAuthStateChanged(auth,async u=>{currentUser=u;if(!u){$('loginPanel').style.display='block';$('managerPanel').style.display='none';$('logout').style.display='none';authStatus('Please sign in with the admin email: '+ADMIN_EMAIL,'');return;}if((u.email||'').toLowerCase()!==ADMIN_EMAIL){$('loginPanel').style.display='block';$('managerPanel').style.display='none';$('logout').style.display='inline-block';authStatus('Signed in as '+u.email+', but this account is not the Product Manager admin. Use '+ADMIN_EMAIL+'.','bad');return;}$('loginPanel').style.display='none';$('managerPanel').style.display='block';$('logout').style.display='inline-block';await load();});
